version: 2
jobs:
  proxy_tests:
    docker:
      - image: mnot/node-server
      - image: mnot/squid
    steps:
      - checkout
      - run: npm install
      - run:
          name: run test server
          background: Y
          command: npm run server --port=8000
      - run:
          name: test squid
          command: npm run --silent cli --base=http://localhost:8001
      - run:
          name: test nginx
          command: npm run --silent cli --base=http://localhost:8002
workflows:
  version: 2
  test:
    jobs:
      - proxy_tests
