version: 2
jobs:
  proxy_tests:
    docker:
      - image: mnot/node-server
      - image: mnot/squid
      - image: mnot/nginx
      - image: mnot/trafficserver
    steps:
      - checkout
      - run: npm install
      - run:
          name: run test server
          background: Y
          command: npm run server --port=8000
      - run:
          name: test squid
          command: npm run --silent cli --base=http://localhost:8001
      - run:
          name: test nginx
          command: npm run --silent cli --base=http://localhost:8002
      - run:
          name: test trafficserver
          command: npm run --silent cli --base=http://localhost:8003
      - deploy:
          name: Upload results
          command: |
            git config user.email "mnot@mnot.net"
            git config user.name "CI"
            git add results/*.json
            git commit --allow-empty -m "Update results"
            git push -q https://${GH_TOKEN}@github.com/http-tests/cache-tests.git master
workflows:
  version: 2
  test:
    jobs:
      - proxy_tests
