name: Lint

on: [push, pull_request]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install -g standard ajv
    - run: npm run lint
    - run: npm run validate
